services:

  db:
    container_name: management-db
    image: postgres:17.2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ManagementApi
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U spark -d spark-vibe" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  pgadmin:
    container_name: management-pgadmin
    image: dpage/pgadmin4:8.14.0
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - data-pgadmin-service:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
  
  rabbitmq:
    container_name: management-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    # RabbitMQ mesajlaşma portu
      - "15672:15672"  # Yönetim paneli portu
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

volumes:
  data-pgadmin-service: